name: Spiro Design Deploy For web

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: ./zstd_wasm_builder

    - name: build
      run: make web-build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web_page
