name: Spiro Design Deploy For web

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'

    - name: Install Depencies Python package
      run: pip install -r requirements.txt

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: ./zstd_wasm_builder

    - name: build
      run: make web-build

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./web_page

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
